from datetime import datetime, timezone
from typing import List

from fastapi import (
    APIRouter,
    Depends,
    HTTPException
)

from sqlalchemy.orm import Session

from app.auth.dependencies import require_roles
from app.database import get_db
from app.models.product import Product
from app.models.scan_event import ScanEvent

from app.schemas import (
    ScanCreate,
    PublicScanCreate,
    ScanResponse,
    ReviewUpdate
)

from app.services.detection import (
    check_impossible_travel,
    check_high_frequency,
    check_code_format
)


router = APIRouter(
    prefix="/scan",
    tags=["Scans"]
)


def create_scan_event(
    scan_code: str,
    latitude: float,
    longitude: float,
    location_accuracy: float | None,
    db: Session
):
    """
    Create a TrustTrace scan event.

    The timestamp is always generated by the server.
    Client-provided timestamps are never trusted.
    """

    product = (
        db.query(Product)
        .filter(Product.code == scan_code)
        .first()
    )

    if not product:
        raise HTTPException(
            status_code=404,
            detail="Product code not registered"
        )

    timestamp = datetime.now(timezone.utc)

    flag_reasons = []

    code_format_reason = check_code_format(
        scan_code
    )

    if code_format_reason:
        flag_reasons.append(
            code_format_reason
        )

    impossible_travel_reason = (
        check_impossible_travel(
            db=db,
            code=scan_code,
            timestamp=timestamp,
            latitude=latitude,
            longitude=longitude
        )
    )

    if impossible_travel_reason:
        flag_reasons.append(
            impossible_travel_reason
        )

    high_frequency_reason = (
        check_high_frequency(
            db=db,
            code=scan_code,
            timestamp=timestamp
        )
    )

    if high_frequency_reason:
        flag_reasons.append(
            high_frequency_reason
        )

    flag_reason = (
        "; ".join(flag_reasons)
        if flag_reasons
        else None
    )

    scan_event = ScanEvent(
        code=scan_code,
        timestamp=timestamp,
        latitude=latitude,
        longitude=longitude,
        location_accuracy=location_accuracy,
        flagged=bool(flag_reasons),
        flag_reason=flag_reason,
        review_status=(
            "PENDING"
            if flag_reasons
            else "REVIEWED"
        )
    )

    db.add(scan_event)
    db.commit()
    db.refresh(scan_event)

    return scan_event


# =========================================================
# PUBLIC QR SCAN
# =========================================================

@router.post(
    "/public",
    response_model=ScanResponse
)
def public_scan(
    scan: PublicScanCreate,
    db: Session = Depends(get_db)
):
    """
    Public scan endpoint used by the TrustTrace QR scanner.

    This endpoint does not require dashboard authentication.

    Location comes from the scanning browser/device.
    Timestamp comes from the TrustTrace server.
    """

    return create_scan_event(
        scan_code=scan.code,
        latitude=scan.latitude,
        longitude=scan.longitude,
        location_accuracy=scan.location_accuracy,
        db=db
    )


# =========================================================
# AUTHENTICATED STAFF SCAN
# =========================================================

@router.post(
    "/",
    response_model=ScanResponse,
    dependencies=[
        Depends(
            require_roles(
                "super_admin",
                "brand_admin",
                "staff"
            )
        )
    ]
)
def log_scan(
    scan: ScanCreate,
    db: Session = Depends(get_db)
):
    """
    Authenticated staff scan.

    The timestamp supplied by the client is ignored.
    TrustTrace generates the timestamp on the server.
    """

    return create_scan_event(
        scan_code=scan.code,
        latitude=scan.latitude,
        longitude=scan.longitude,
        location_accuracy=scan.location_accuracy,
        db=db
    )


# =========================================================
# ALL SCANS
# =========================================================

@router.get(
    "/",
    response_model=List[ScanResponse],
    dependencies=[
        Depends(
            require_roles(
                "super_admin",
                "brand_admin",
                "investigator",
                "staff"
            )
        )
    ]
)
def get_scans(
    db: Session = Depends(get_db)
):
    return (
        db.query(ScanEvent)
        .order_by(
            ScanEvent.timestamp.desc()
        )
        .all()
    )


# =========================================================
# FLAGGED SCANS
# =========================================================

@router.get(
    "/flags",
    response_model=List[ScanResponse],
    dependencies=[
        Depends(
            require_roles(
                "super_admin",
                "brand_admin",
                "investigator"
            )
        )
    ]
)
def get_flagged_scans(
    db: Session = Depends(get_db)
):
    return (
        db.query(ScanEvent)
        .filter(
            ScanEvent.flagged.is_(True)
        )
        .order_by(
            ScanEvent.timestamp.desc()
        )
        .all()
    )


# =========================================================
# REVIEW SCAN
# =========================================================

@router.patch(
    "/{scan_id}/review",
    response_model=ScanResponse,
    dependencies=[
        Depends(
            require_roles(
                "super_admin",
                "investigator"
            )
        )
    ]
)
def review_scan(
    scan_id: int,
    review: ReviewUpdate,
    db: Session = Depends(get_db)
):
    allowed_statuses = {
        "REVIEWED",
        "DISMISSED"
    }

    if review.review_status not in allowed_statuses:
        raise HTTPException(
            status_code=400,
            detail=(
                "Review status must be "
                "REVIEWED or DISMISSED"
            )
        )

    scan_event = (
        db.query(ScanEvent)
        .filter(
            ScanEvent.id == scan_id
        )
        .first()
    )

    if not scan_event:
        raise HTTPException(
            status_code=404,
            detail="Scan event not found"
        )

    scan_event.review_status = (
        review.review_status
    )

    scan_event.review_note = (
        review.review_note
    )

    scan_event.reviewed_at = (
        datetime.now(timezone.utc)
    )

    db.commit()
    db.refresh(scan_event)

    return scan_event